version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: dao_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dao_alquiler
      MYSQL_USER: dao_user
      MYSQL_PASSWORD: dao_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: dao_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: dao_alquiler
      DB_USER: dao_user
      DB_PASS: dao_pass
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

volumes:
  db_data:
